#!/bin/bash

majorHashDefine="#define CV_VERSION_MAJOR"
minorHashDefine="#define CV_VERSION_MINOR"
revisionHashDefine="#define CV_VERSION_REVISION"
statusHashDefine="#define CV_VERSION_STATUS"

if [ -n "$1" ] && [ -e $1 ];then
	echo "File exists!"
	minorVersion=$(grep "${minorHashDefine}" $1 | grep -o ".$")
	majorVersion=$(grep "${majorHashDefine}" $1 | grep -o ".$")
	revision=$(grep "${revisionHashDefine}" $1 | grep -o ".$")

	echo "The version number will be ${majorVersion}.${minorVersion}.${revision}"
else
	echo "Could not locate file $1 to determine versioning."
	exit 1
fi
